export const theme = {
  dark: false,
  colors: {
    primary: 'rgb(52, 95, 181)',
    onPrimary: 'rgb(255, 255, 255)',
    primaryContainer: 'rgb(240, 219, 255)',
    onPrimaryContainer: 'rgb(44, 0, 81)',
    secondary: 'rgb(102, 90, 111)',
    onSecondary: 'rgb(255, 255, 255)',
    secondaryContainer: 'rgb(237, 221, 246)',
    onSecondaryContainer: 'rgb(33, 24, 42)',
    tertiary: 'rgb(128, 81, 88)',
    onTertiary: 'rgb(255, 255, 255)',
    tertiaryContainer: 'rgb(255, 217, 221)',
    onTertiaryContainer: 'rgb(50, 16, 23)',
    error: 'rgb(186, 26, 26)',
    onError: 'rgb(255, 255, 255)',
    errorContainer: 'rgb(255, 218, 214)',
    onErrorContainer: 'rgb(65, 0, 2)',
    background: 'rgb(255, 251, 255)',
    onBackground: 'rgb(29, 27, 30)',
    surface: 'rgb(255, 251, 255)',
    onSurface: 'rgb(29, 27, 30)',
    surfaceVariant: 'rgb(233, 223, 235)',
    onSurfaceVariant: 'rgb(74, 69, 78)',
    outline: 'rgb(124, 117, 126)',
    outlineVariant: 'rgb(204, 196, 206)',
    shadow: 'rgb(0, 0, 0)',
    scrim: 'rgb(0, 0, 0)',
    inverseSurface: 'rgb(50, 47, 51)',
    inverseOnSurface: 'rgb(245, 239, 244)',
    inversePrimary: 'rgb(220, 184, 255)',
    elevation: {
      level0: 'transparent',
      level1: 'rgb(248, 242, 251)',
      level2: 'rgb(244, 236, 248)',
      level3: 'rgb(240, 231, 246)',
      level4: 'rgb(239, 229, 245)',
      level5: 'rgb(236, 226, 243)',
    },
    surfaceDisabled: 'rgba(29, 27, 30, 0.12)',
    onSurfaceDisabled: 'rgba(29, 27, 30, 0.38)',
    backdrop: 'rgba(51, 47, 55, 0.4)',
  },
};

export const settings = {
  rippleEffectEnabled: true,
};

export const dataStates = [
  {
    'ID State': '04000US01',
    State: 'Alabama',
    'ID Year': 2021,
    Year: '2021',
    Population: 4997675,
    'Slug State': 'alabama',
  },
  {
    'ID State': '04000US02',
    State: 'Alaska',
    'ID Year': 2021,
    Year: '2021',
    Population: 735951,
    'Slug State': 'alaska',
  },
  {
    'ID State': '04000US04',
    State: 'Arizona',
    'ID Year': 2021,
    Year: '2021',
    Population: 7079203,
    'Slug State': 'arizona',
  },
  {
    'ID State': '04000US05',
    State: 'Arkansas',
    'ID Year': 2021,
    Year: '2021',
    Population: 3006309,
    'Slug State': 'arkansas',
  },
  {
    'ID State': '04000US06',
    State: 'California',
    'ID Year': 2021,
    Year: '2021',
    Population: 39455353,
    'Slug State': 'california',
  },
  {
    'ID State': '04000US08',
    State: 'Colorado',
    'ID Year': 2021,
    Year: '2021',
    Population: 5723176,
    'Slug State': 'colorado',
  },
  {
    'ID State': '04000US09',
    State: 'Connecticut',
    'ID Year': 2021,
    Year: '2021',
    Population: 3605330,
    'Slug State': 'connecticut',
  },
  {
    'ID State': '04000US10',
    State: 'Delaware',
    'ID Year': 2021,
    Year: '2021',
    Population: 981892,
    'Slug State': 'delaware',
  },
  {
    'ID State': '04000US11',
    State: 'District of Columbia',
    'ID Year': 2021,
    Year: '2021',
    Population: 683154,
    'Slug State': 'district-of-columbia',
  },
  {
    'ID State': '04000US12',
    State: 'Florida',
    'ID Year': 2021,
    Year: '2021',
    Population: 21339762,
    'Slug State': 'florida',
  },
  {
    'ID State': '04000US13',
    State: 'Georgia',
    'ID Year': 2021,
    Year: '2021',
    Population: 10625615,
    'Slug State': 'georgia',
  },
  {
    'ID State': '04000US15',
    State: 'Hawaii',
    'ID Year': 2021,
    Year: '2021',
    Population: 1453498,
    'Slug State': 'hawaii',
  },
  {
    'ID State': '04000US16',
    State: 'Idaho',
    'ID Year': 2021,
    Year: '2021',
    Population: 1811617,
    'Slug State': 'idaho',
  },
  {
    'ID State': '04000US17',
    State: 'Illinois',
    'ID Year': 2021,
    Year: '2021',
    Population: 12821813,
    'Slug State': 'illinois',
  },
  {
    'ID State': '04000US18',
    State: 'Indiana',
    'ID Year': 2021,
    Year: '2021',
    Population: 6751340,
    'Slug State': 'indiana',
  },
  {
    'ID State': '04000US19',
    State: 'Iowa',
    'ID Year': 2021,
    Year: '2021',
    Population: 3179090,
    'Slug State': 'iowa',
  },
  {
    'ID State': '04000US20',
    State: 'Kansas',
    'ID Year': 2021,
    Year: '2021',
    Population: 2932099,
    'Slug State': 'kansas',
  },
  {
    'ID State': '04000US21',
    State: 'Kentucky',
    'ID Year': 2021,
    Year: '2021',
    Population: 4494141,
    'Slug State': 'kentucky',
  },
  {
    'ID State': '04000US22',
    State: 'Louisiana',
    'ID Year': 2021,
    Year: '2021',
    Population: 4657305,
    'Slug State': 'louisiana',
  },
  {
    'ID State': '04000US23',
    State: 'Maine',
    'ID Year': 2021,
    Year: '2021',
    Population: 1357046,
    'Slug State': 'maine',
  },
  {
    'ID State': '04000US24',
    State: 'Maryland',
    'ID Year': 2021,
    Year: '2021',
    Population: 6148545,
    'Slug State': 'maryland',
  },
  {
    'ID State': '04000US25',
    State: 'Massachusetts',
    'ID Year': 2021,
    Year: '2021',
    Population: 6991852,
    'Slug State': 'massachusetts',
  },
  {
    'ID State': '04000US26',
    State: 'Michigan',
    'ID Year': 2021,
    Year: '2021',
    Population: 10062512,
    'Slug State': 'michigan',
  },
  {
    'ID State': '04000US27',
    State: 'Minnesota',
    'ID Year': 2021,
    Year: '2021',
    Population: 5670472,
    'Slug State': 'minnesota',
  },
  {
    'ID State': '04000US28',
    State: 'Mississippi',
    'ID Year': 2021,
    Year: '2021',
    Population: 2967023,
    'Slug State': 'mississippi',
  },
  {
    'ID State': '04000US29',
    State: 'Missouri',
    'ID Year': 2021,
    Year: '2021',
    Population: 6141534,
    'Slug State': 'missouri',
  },
  {
    'ID State': '04000US30',
    State: 'Montana',
    'ID Year': 2021,
    Year: '2021',
    Population: 1077978,
    'Slug State': 'montana',
  },
  {
    'ID State': '04000US31',
    State: 'Nebraska',
    'ID Year': 2021,
    Year: '2021',
    Population: 1951480,
    'Slug State': 'nebraska',
  },
  {
    'ID State': '04000US32',
    State: 'Nevada',
    'ID Year': 2021,
    Year: '2021',
    Population: 3059238,
    'Slug State': 'nevada',
  },
  {
    'ID State': '04000US33',
    State: 'New Hampshire',
    'ID Year': 2021,
    Year: '2021',
    Population: 1372175,
    'Slug State': 'new-hampshire',
  },
  {
    'ID State': '04000US34',
    State: 'New Jersey',
    'ID Year': 2021,
    Year: '2021',
    Population: 9234024,
    'Slug State': 'new-jersey',
  },
  {
    'ID State': '04000US35',
    State: 'New Mexico',
    'ID Year': 2021,
    Year: '2021',
    Population: 2109366,
    'Slug State': 'new-mexico',
  },
  {
    'ID State': '04000US36',
    State: 'New York',
    'ID Year': 2021,
    Year: '2021',
    Population: 20114745,
    'Slug State': 'new-york',
  },
  {
    'ID State': '04000US37',
    State: 'North Carolina',
    'ID Year': 2021,
    Year: '2021',
    Population: 10367022,
    'Slug State': 'north-carolina',
  },
  {
    'ID State': '04000US38',
    State: 'North Dakota',
    'ID Year': 2021,
    Year: '2021',
    Population: 773344,
    'Slug State': 'north-dakota',
  },
  {
    'ID State': '04000US39',
    State: 'Ohio',
    'ID Year': 2021,
    Year: '2021',
    Population: 11769923,
    'Slug State': 'ohio',
  },
  {
    'ID State': '04000US40',
    State: 'Oklahoma',
    'ID Year': 2021,
    Year: '2021',
    Population: 3948136,
    'Slug State': 'oklahoma',
  },
  {
    'ID State': '04000US41',
    State: 'Oregon',
    'ID Year': 2021,
    Year: '2021',
    Population: 4207177,
    'Slug State': 'oregon',
  },
  {
    'ID State': '04000US42',
    State: 'Pennsylvania',
    'ID Year': 2021,
    Year: '2021',
    Population: 12970650,
    'Slug State': 'pennsylvania',
  },
  {
    'ID State': '04000US44',
    State: 'Rhode Island',
    'ID Year': 2021,
    Year: '2021',
    Population: 1091949,
    'Slug State': 'rhode-island',
  },
  {
    'ID State': '04000US45',
    State: 'South Carolina',
    'ID Year': 2021,
    Year: '2021',
    Population: 5078903,
    'Slug State': 'south-carolina',
  },
  {
    'ID State': '04000US46',
    State: 'South Dakota',
    'ID Year': 2021,
    Year: '2021',
    Population: 881785,
    'Slug State': 'south-dakota',
  },
  {
    'ID State': '04000US47',
    State: 'Tennessee',
    'ID Year': 2021,
    Year: '2021',
    Population: 6859497,
    'Slug State': 'tennessee',
  },
  {
    'ID State': '04000US48',
    State: 'Texas',
    'ID Year': 2021,
    Year: '2021',
    Population: 28862581,
    'Slug State': 'texas',
  },
  {
    'ID State': '04000US49',
    State: 'Utah',
    'ID Year': 2021,
    Year: '2021',
    Population: 3231370,
    'Slug State': 'utah',
  },
  {
    'ID State': '04000US50',
    State: 'Vermont',
    'ID Year': 2021,
    Year: '2021',
    Population: 641637,
    'Slug State': 'vermont',
  },
  {
    'ID State': '04000US51',
    State: 'Virginia',
    'ID Year': 2021,
    Year: '2021',
    Population: 8582479,
    'Slug State': 'virginia',
  },
  {
    'ID State': '04000US53',
    State: 'Washington',
    'ID Year': 2021,
    Year: '2021',
    Population: 7617364,
    'Slug State': 'washington',
  },
  {
    'ID State': '04000US54',
    State: 'West Virginia',
    'ID Year': 2021,
    Year: '2021',
    Population: 1801049,
    'Slug State': 'west-virginia',
  },
  {
    'ID State': '04000US55',
    State: 'Wisconsin',
    'ID Year': 2021,
    Year: '2021',
    Population: 5871661,
    'Slug State': 'wisconsin',
  },
  {
    'ID State': '04000US56',
    State: 'Wyoming',
    'ID Year': 2021,
    Year: '2021',
    Population: 576641,
    'Slug State': 'wyoming',
  },
  {
    'ID State': '04000US72',
    State: 'Puerto Rico',
    'ID Year': 2021,
    Year: '2021',
    Population: 3311274,
    'Slug State': 'puerto-rico',
  },
];

export const dataFlag = [
  [
    'Alabama',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Alabama.svg/250px-Flag_of_Alabama.svg.png',
  ],
  [
    'Alaska',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Alaska.svg/250px-Flag_of_Alaska.svg.png',
  ],
  [
    'Arizona',
    'https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Arizona.svg',
  ],
  [
    'Arkansas',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Arkansas.svg/250px-Flag_of_Arkansas.svg.png',
  ],
  [
    'California',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_California.svg/640px-Flag_of_California.svg.png',
  ],
  [
    'District of Columbia',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_the_District_of_Columbia.svg/125px-Flag_of_the_District_of_Columbia.svg.png',
  ],
  [
    'Colorado',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Flag_of_Colorado.svg/125px-Flag_of_Colorado.svg.png',
  ],
  [
    'Connecticut',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Flag_of_Connecticut.svg/621px-Flag_of_Connecticut.svg.png',
    1,
  ],
  [
    'Delaware',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Flag_of_Delaware.svg/640px-Flag_of_Delaware.svg.png',
    1,
  ],
  [
    'Florida',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Flag_of_Florida.svg/640px-Flag_of_Florida.svg.png',
  ],
  [
    'Georgia',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Flag_of_Georgia_%28U.S._state%29.svg/640px-Flag_of_Georgia_%28U.S._state%29.svg.png',
  ],
  [
    'Hawaii',
    'https://upload.wikimedia.org/wikipedia/commons/e/ef/Flag_of_Hawaii.svg',
  ],
  [
    'Idaho',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_Idaho.svg/609px-Flag_of_Idaho.svg.png',
  ],
  [
    'Illinois',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Illinois.svg/800px-Flag_of_Illinois.svg.png',
  ],
  [
    'Indiana',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Flag_of_Indiana.svg/250px-Flag_of_Indiana.svg.png',
  ],
  [
    'Iowa',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Flag_of_Iowa.svg/640px-Flag_of_Iowa.svg.png',
  ],
  [
    'Kansas',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Flag_of_Kansas.svg/800px-Flag_of_Kansas.svg.png',
  ],
  [
    'Kentucky',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Flag_of_Kentucky.svg/640px-Flag_of_Kentucky.svg.png',
  ],
  [
    'Louisiana',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Flag_of_Louisiana.svg/640px-Flag_of_Louisiana.svg.png',
  ],
  [
    'Maine',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Flag_of_Maine.svg/640px-Flag_of_Maine.svg.png',
  ],
  [
    'Maryland',
    'https://upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_Maryland.svg',
  ],
  [
    'Massachusetts',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Flag_of_Massachusetts.svg/800px-Flag_of_Massachusetts.svg.png',
  ],
  [
    'Michigan',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Flag_of_Michigan.svg/640px-Flag_of_Michigan.svg.png',
  ],
  [
    'Minnesota',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Minnesota.svg/640px-Flag_of_Minnesota.svg.png',
  ],
  [
    'Mississippi',
    'https://upload.wikimedia.org/wikipedia/commons/4/42/Flag_of_Mississippi.svg',
  ],
  [
    'Missouri',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Flag_of_Missouri.svg/640px-Flag_of_Missouri.svg.png',
  ],
  [
    'Montana',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_Montana.svg/640px-Flag_of_Montana.svg.png',
  ],
  [
    'Nebraska',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Flag_of_Nebraska.svg/640px-Flag_of_Nebraska.svg.png',
  ],
  [
    'Nevada',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Flag_of_Nevada.svg/640px-Flag_of_Nevada.svg.png',
  ],
  [
    'New Hampshire',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Flag_of_New_Hampshire.svg/640px-Flag_of_New_Hampshire.svg.png',
  ],
  [
    'New Jersey',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_New_Jersey.svg/640px-Flag_of_New_Jersey.svg.png',
  ],
  [
    'New Mexico',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_New_Mexico.svg/800px-Flag_of_New_Mexico.svg.png',
  ],
  [
    'New York',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_New_York.svg/640px-Flag_of_New_York.svg.png',
  ],
  [
    'North Carolina',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Flag_of_North_Carolina.svg/250px-Flag_of_North_Carolina.svg.png',
  ],
  [
    'North Dakota',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Flag_of_North_Dakota.svg/613px-Flag_of_North_Dakota.svg.png',
  ],
  [
    'Ohio',
    'https://upload.wikimedia.org/wikipedia/commons/4/4c/Flag_of_Ohio.svg',
  ],
  [
    'Oklahoma',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Flag_of_Oklahoma.svg/640px-Flag_of_Oklahoma.svg.png',
  ],
  [
    'Oregon',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Oregon.svg/640px-Flag_of_Oregon.svg.png',
  ],
  [
    'Pennsylvania',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Flag_of_Pennsylvania.svg/640px-Flag_of_Pennsylvania.svg.png',
  ],
  [
    'Rhode Island',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Rhode_Island.svg/250px-Flag_of_Rhode_Island.svg.png',
  ],
  [
    'South Carolina',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Flag_of_South_Carolina.svg/640px-Flag_of_South_Carolina.svg.png',
  ],
  [
    'South Dakota',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_South_Dakota.svg/640px-Flag_of_South_Dakota.svg.png',
  ],
  [
    'Tennessee',
    'https://upload.wikimedia.org/wikipedia/commons/9/9e/Flag_of_Tennessee.svg',
  ],
  [
    'Texas',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Flag_of_Texas.svg/250px-Flag_of_Texas.svg.png',
  ],
  [
    'Utah',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Utah.svg/320px-Flag_of_Utah.svg.png',
  ],
  [
    'Vermont',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Vermont.svg/640px-Flag_of_Vermont.svg.png',
  ],
  [
    'Virginia',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Flag_of_Virginia.svg/640px-Flag_of_Virginia.svg.png',
  ],
  [
    'Washington',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Flag_of_Washington.svg/640px-Flag_of_Washington.svg.png',
  ],
  [
    'West Virginia',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Flag_of_West_Virginia.svg/640px-Flag_of_West_Virginia.svg.png',
  ],
  [
    'Wisconsin',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Flag_of_Wisconsin.svg/640px-Flag_of_Wisconsin.svg.png',
  ],
  [
    'Wyoming',
    'https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Wyoming.svg',
  ],
  [
    'Puerto Rico',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Flag_of_Puerto_Rico.svg/125px-Flag_of_Puerto_Rico.svg.png',
  ],
];
